version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./.next:/app/.next
      - ./node_modules:/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge